server/auth/linkedin.js
This is the proper formatting to pull the email address from LinkedIn's API
=> Properly pull emailAddress from LinkedIn

server/auth/google.js
This is the proper formatting to pull the email address from Google's API
=> Properly pull email from Google

server/auth/twitter.js
This is the proper formatting to pull the email address from Twitter's API
=> Properly pull email attribute from Google

README.md
Happens to get rid of the 404 issue as well.
=> Making links version-agnostic

server/routes.js
Related to issue #84 
normalizing idp filename and handling NOENT errors (so error doesn't return full path)
=> 84 idp param security handle

server/routes.js
Changing normalize regex to basepath method.
=> changed normalize regex for basepath for cleaner code - changing for basepath

package-lock.json, package.json
=> Fixing serialize-javascript test vulnerability

.github/workflows/branchmerger.yml
Automatically merging master -> version_4.2.1 on push (==merge)
=> Automatically merging master -> version_4.2.1

.github/workflows/branchmerger.yml
For now we are merging on master.
=> Disabling auto-merge branches on pipeline

server/providers.js, test/providers.test.js
As We are using Standardjs code linting so I fixed the problem by updating the key in `passportStrategies` array from `strategy` to `Strategy`. I checked and tested the flow as per define in the issue. It is working good now.
close #119
=> fix: solved the provider update strategy problem #119

package-lock.json, package.json
=> build: bump passport-saml and xml-crypto closes #124

.npmrc, CHANGELOG.md, package-lock.json, package.json
Node version needs to be `>=12.19.0 <13.0.0` otherwise will not be installed
=> Build enforce node version

.github/workflows/codeql.yml
=> ci(codeql.yml): add CodeQL to github action

README.md, package-lock.json, package.json, server/routes.js, test/routes.test.js, test/testdata/init-mock.js
Mitigate cross origin from error handling
closes #137
=> fix(routes.js): remove received input from error output msg

CHANGELOG.md, package-lock.json, package.json
=> chore(release): 4.4.0

.github/workflows/commit-check.yml
Preparation for the move of workflows centrally
=> ci(commit-check): sync workflows

package-lock.json
Fix underscore vunlerability and update other deps
=> fix(dependencies): relock file to fix vulnerability

.github/workflows/codecov.yml, .github/workflows/lint.yml, package-lock.json, package.json
node-xtraverse fix and pr https://github.com/GluuFederation/node-xtraverse/pull/1
passport-twitter fix and pr https://github.com/GluuFederation/passport-twitter/pull/1
close #265
=> Fix Twitter strategy vulnerability

test/logging.test.js
=> fix(logging.test.js): fix empty dirname and use existing log dir path

server/utils/uma.js, test/uma.test.js
=> fix: remove decimal points from Client assertion JWT exp time

package-lock.json
update deps tree on package-lock.json
=> fix(package-lock.json): update node-xtraverse due to vulnerability in xmldom

CHANGELOG.md, package-lock.json, package.json
Release hotfix for gluu-passport 4.x
=> chore(release): 4.6.1

server/providers.js, test/providers.test.js
=> fix: change log level to `debug` as `silly` is not used

.github/workflows/branchmerger.yml
automatic merge master to `version_4.3.1` branch (gluu-server)
=> ci: activate branch merger for 4.3.1

package-lock.json
=> fix(security): update deps for passport-oauth2 

package-lock.json, package.json, server/extra-passport-params.js
=> fix!: remove deprecated passport-oxd

package-lock.json, package.json
=> fix(security): fix `passport-apple` jsonwebtoken
